# Generated by Django 5.0.7 on 2024-09-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_text_predictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='hate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='text',
            name='not_hate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
